# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false

cache: packages

r_packages:
  - covr
  - devtools

before_script:
  - sudo apt-get update
  - sudo apt-get install python3 python3-pip
  - pip3 install --upgrade --ignore-installed --user travis virtualenv
  - R CMD INSTALL .
  - R -e 'keras::install_keras(tensorflow = Sys.getenv("TENSORFLOW_VERSION"), extra_packages = "IPython")'
  - R -e 'tensorflow::tf_config()'

after_success:
  - Rscript -e 'covr::codecov()'
